apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.be.name }}
  name: {{ .Values.be.name }}
spec:
  ports:
    - name: {{ .Values.be.name }}-ports
      port: {{ .Values.be.service.port }}
      protocol: {{ .Values.be.service.protocol }}
      targetPort: {{ .Values.be.service.targetPort }}
  selector:
    app: {{ .Values.be.name }}
  type: {{ .Values.be.service.type }}