{{- if .Values.be.java_secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.be.name }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.be.java_secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}