apiVersion: v1
data:
  APP_TITLE: {{ .Values.fe.ui_settings.app_title | quote }}
kind: ConfigMap
metadata:
  name: {{ .Values.fe.name }}
  labels:
    app: {{ .Values.fe.name }}
    {{- include "fe.labels" . | indent 4 }}